"""Schema invariant tests for StreetSense's append-only score tables.

These tests enforce the non-negotiable invariants from CLAUDE.md and
workflow.md against a freshly migrated database:

1. road_segments has the expected columns and a GIST index on geometry.
2. scoring_runs has a timestamp column with a BTREE index.
3. segment_scores has all six reproducibility fields, each NOT NULL.
4. UPDATE / DELETE on scoring_runs and segment_scores are denied to the
   application role.
5. Primary keys are UUIDs generated by gen_random_uuid(), never SERIAL.

If any of these regress, the migration that broke them never lands.
"""

from __future__ import annotations

from typing import Any
from uuid import UUID

import psycopg
import pytest
from psycopg import errors as pg_errors

pytestmark = pytest.mark.integration


# --- Helpers --------------------------------------------------------------
def _column_info(
    conn: psycopg.Connection[Any], table: str
) -> dict[str, tuple[str, str, str | None]]:
    """Return a mapping {column_name: (data_type, is_nullable, column_default)}."""
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT column_name, data_type, is_nullable, column_default
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = %s
            """,
            (table,),
        )
        return {row[0]: (row[1], row[2], row[3]) for row in cur.fetchall()}


def _index_definitions(conn: psycopg.Connection[Any], table: str) -> list[str]:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT indexdef FROM pg_indexes WHERE schemaname = 'public' AND tablename = %s",
            (table,),
        )
        return [row[0] for row in cur.fetchall()]


def _primary_key_column(conn: psycopg.Connection[Any], table: str) -> str:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT a.attname
            FROM pg_index i
            JOIN pg_attribute a
              ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
            WHERE i.indrelid = %s::regclass AND i.indisprimary
            """,
            (f"public.{table}",),
        )
        rows = cur.fetchall()
        assert len(rows) == 1, f"Expected single-column PK on {table}, got {rows}"
        return str(rows[0][0])


# --- road_segments --------------------------------------------------------
class TestRoadSegments:
    def test_table_exists_with_expected_columns(self, owner_conn: psycopg.Connection[Any]) -> None:
        cols = _column_info(owner_conn, "road_segments")
        assert "id" in cols
        assert "geometry" in cols
        assert "osm_way_id" in cols
        assert "attrs" in cols

    def test_id_is_uuid_with_gen_random_uuid_default(
        self, owner_conn: psycopg.Connection[Any]
    ) -> None:
        cols = _column_info(owner_conn, "road_segments")
        data_type, is_nullable, default = cols["id"]
        assert data_type == "uuid"
        assert is_nullable == "NO"
        assert default is not None
        assert "gen_random_uuid" in default
        assert "nextval" not in default  # not SERIAL

    def test_geometry_is_linestring_4326_not_null(
        self, owner_conn: psycopg.Connection[Any]
    ) -> None:
        cols = _column_info(owner_conn, "road_segments")
        _data_type, is_nullable, _default = cols["geometry"]
        assert is_nullable == "NO"
        with owner_conn.cursor() as cur:
            cur.execute(
                """
                SELECT type, srid
                FROM geometry_columns
                WHERE f_table_schema = 'public' AND f_table_name = 'road_segments'
                  AND f_geometry_column = 'geometry'
                """,
            )
            row = cur.fetchone()
            assert row is not None, "geometry_columns has no entry for road_segments.geometry"
            geom_type, srid = row
            assert geom_type == "LINESTRING"
            assert srid == 4326

    def test_gist_index_on_geometry(self, owner_conn: psycopg.Connection[Any]) -> None:
        defs = _index_definitions(owner_conn, "road_segments")
        gist = [d for d in defs if "using gist" in d.lower() and "geometry" in d.lower()]
        assert gist, f"No GIST index on road_segments.geometry. Found: {defs}"

    def test_attrs_is_jsonb(self, owner_conn: psycopg.Connection[Any]) -> None:
        cols = _column_info(owner_conn, "road_segments")
        assert cols["attrs"][0] == "jsonb"


# --- scoring_runs ---------------------------------------------------------
class TestScoringRuns:
    def test_table_exists_with_uuid_pk(self, owner_conn: psycopg.Connection[Any]) -> None:
        pk = _primary_key_column(owner_conn, "scoring_runs")
        assert pk == "id"
        cols = _column_info(owner_conn, "scoring_runs")
        assert cols["id"][0] == "uuid"
        assert cols["id"][2] is not None
        assert "gen_random_uuid" in cols["id"][2]

    def test_timestamp_column_not_null(self, owner_conn: psycopg.Connection[Any]) -> None:
        cols = _column_info(owner_conn, "scoring_runs")
        # Per CLAUDE.md: "scoring_runs(id uuid pk, timestamp timestamptz not null, ...)"
        ts_col = "scoring_run_timestamp" if "scoring_run_timestamp" in cols else "timestamp"
        assert ts_col in cols, f"scoring_runs missing timestamp column; have: {list(cols)}"
        data_type, is_nullable, _ = cols[ts_col]
        assert "timestamp" in data_type
        assert is_nullable == "NO"

    def test_btree_index_on_timestamp(self, owner_conn: psycopg.Connection[Any]) -> None:
        defs = _index_definitions(owner_conn, "scoring_runs")
        cols = _column_info(owner_conn, "scoring_runs")
        ts_col = "scoring_run_timestamp" if "scoring_run_timestamp" in cols else "timestamp"
        # PG default index is btree; either explicit "USING btree" or omitted.
        has_btree = any(
            ts_col in d and ("USING btree" in d.lower() or "using btree" in d.lower()) for d in defs
        )
        assert has_btree, f"No BTREE index on scoring_runs.{ts_col}. Found: {defs}"


# --- segment_scores: the six reproducibility fields -----------------------
REPRODUCIBILITY_COLUMNS = (
    "scoring_run_id",
    "scoring_run_timestamp",
    "perception_model_version",
    "osm_snapshot_date",
    "imagery_capture_window",
    "propagation_algorithm_version",
)


class TestSegmentScoresReproducibility:
    def test_all_six_reproducibility_columns_exist(
        self, owner_conn: psycopg.Connection[Any]
    ) -> None:
        cols = _column_info(owner_conn, "segment_scores")
        missing = [c for c in REPRODUCIBILITY_COLUMNS if c not in cols]
        assert not missing, f"segment_scores missing reproducibility columns: {missing}"

    @pytest.mark.parametrize("column", REPRODUCIBILITY_COLUMNS)
    def test_each_reproducibility_column_is_not_null(
        self, owner_conn: psycopg.Connection[Any], column: str
    ) -> None:
        cols = _column_info(owner_conn, "segment_scores")
        _, is_nullable, _ = cols[column]
        assert is_nullable == "NO", f"{column} must be NOT NULL"

    def test_insert_omitting_any_reproducibility_field_fails(
        self, owner_conn: psycopg.Connection[Any]
    ) -> None:
        """A NOT NULL constraint must trip on every missing reproducibility field."""
        # Build a row that satisfies non-reproducibility constraints, then strip each
        # reproducibility field in turn and assert the insert fails.
        with owner_conn.cursor() as cur:
            cur.execute("SELECT id FROM road_segments LIMIT 1")
            row = cur.fetchone()
            if row is None:
                # Insert a placeholder segment so we have a valid FK target.
                cur.execute(
                    """
                    INSERT INTO road_segments (geometry, osm_way_id, attrs)
                    VALUES (
                        ST_SetSRID(ST_MakeLine(ST_MakePoint(0,0), ST_MakePoint(1,1)), 4326),
                        1, '{}'::jsonb
                    )
                    RETURNING id
                    """
                )
                row = cur.fetchone()
                assert row is not None
            segment_id = row[0]
        owner_conn.commit()

        for omitted in REPRODUCIBILITY_COLUMNS:
            fields: dict[str, object] = {
                "segment_id": segment_id,
                "composite_risk": 0.0,
                "scoring_run_id": "00000000-0000-0000-0000-000000000001",
                "scoring_run_timestamp": "2026-01-01T00:00:00Z",
                "perception_model_version": "v0.0.0-stub",
                "osm_snapshot_date": "2026-01-01",
                "imagery_capture_window": "[2026-01-01,2026-01-02)",
                "propagation_algorithm_version": "v0.0.0-stub",
            }
            del fields[omitted]
            cols_sql = ", ".join(fields.keys())
            placeholders = ", ".join(["%s"] * len(fields))
            sql = f"INSERT INTO segment_scores ({cols_sql}) VALUES ({placeholders})"
            with owner_conn.cursor() as cur, pytest.raises(pg_errors.NotNullViolation):
                cur.execute(sql, list(fields.values()))
            owner_conn.rollback()


# --- Per-sub-score is_stub_* flags (Phase 2.3.3) --------------------------
SUB_SCORE_STUB_COLUMNS = (
    "is_stub_lane_marking",
    "is_stub_glare",
    "is_stub_junction_complexity",
    "is_stub_historical",
)


class TestSegmentScoresStubFlags:
    @pytest.mark.parametrize("column", SUB_SCORE_STUB_COLUMNS)
    def test_is_stub_column_exists_and_defaults_true(
        self, owner_conn: psycopg.Connection[Any], column: str
    ) -> None:
        cols = _column_info(owner_conn, "segment_scores")
        assert column in cols, f"segment_scores missing per-sub-score stub column {column}"
        data_type, is_nullable, default = cols[column]
        assert data_type == "boolean"
        assert is_nullable == "NO", f"{column} must be NOT NULL"
        assert default is not None and "true" in default.lower(), (
            f"{column} should default to true; got default={default!r}"
        )


# --- Append-only enforcement at the role level ----------------------------
class TestAppendOnlyAtRoleLevel:
    @pytest.mark.parametrize("table", ["scoring_runs", "segment_scores"])
    def test_update_is_revoked_for_app_role(
        self, app_conn: psycopg.Connection[Any], table: str
    ) -> None:
        with app_conn.cursor() as cur, pytest.raises(pg_errors.InsufficientPrivilege):
            cur.execute(f"UPDATE {table} SET id = id WHERE FALSE")
        app_conn.rollback()

    @pytest.mark.parametrize("table", ["scoring_runs", "segment_scores"])
    def test_delete_is_revoked_for_app_role(
        self, app_conn: psycopg.Connection[Any], table: str
    ) -> None:
        with app_conn.cursor() as cur, pytest.raises(pg_errors.InsufficientPrivilege):
            cur.execute(f"DELETE FROM {table} WHERE FALSE")
        app_conn.rollback()


# --- UUIDs not SERIAL across the board ------------------------------------
class TestUUIDPrimaryKeys:
    @pytest.mark.parametrize("table", ["road_segments", "scoring_runs", "segment_scores"])
    def test_primary_key_is_uuid(self, owner_conn: psycopg.Connection[Any], table: str) -> None:
        pk_col = _primary_key_column(owner_conn, table)
        cols = _column_info(owner_conn, table)
        data_type, _, default = cols[pk_col]
        assert data_type == "uuid", f"{table}.{pk_col} is {data_type}, expected uuid"
        assert default is not None
        assert "gen_random_uuid" in default
        assert "nextval" not in default

    @pytest.mark.parametrize("table", ["road_segments", "scoring_runs", "segment_scores"])
    def test_no_sequences_on_table(self, owner_conn: psycopg.Connection[Any], table: str) -> None:
        with owner_conn.cursor() as cur:
            cur.execute(
                """
                SELECT s.relname
                FROM pg_class s
                JOIN pg_depend d ON d.objid = s.oid AND d.deptype = 'a'
                JOIN pg_class t ON t.oid = d.refobjid
                WHERE s.relkind = 'S' AND t.relname = %s
                """,
                (table,),
            )
            seqs = [row[0] for row in cur.fetchall()]
        assert seqs == [], f"{table} owns sequences (SERIAL?): {seqs}"


# --- Sanity: UUIDs round-trip ---------------------------------------------
def test_uuid_round_trip(owner_conn: psycopg.Connection[Any]) -> None:
    with owner_conn.cursor() as cur:
        cur.execute("SELECT gen_random_uuid()")
        row = cur.fetchone()
        assert row is not None
        uid = row[0]
        assert isinstance(uid, UUID)
