"""Initial StreetSense schema.

Creates the three core tables and locks in the non-negotiable invariants:

- All primary keys are UUIDs generated by gen_random_uuid(), never SERIAL.
- road_segments stores geometry as LineString in WGS84 (4326) with a GIST
  index for spatial queries.
- scoring_runs has a BTREE index on scoring_run_timestamp for time-windowed
  queries.
- segment_scores carries all six reproducibility fields, each NOT NULL —
  failing fast on any scoring run that cannot establish provenance.
- The application role (streetsense_app) is provisioned here, granted the
  least privilege needed to serve reads + record new scoring runs, and has
  UPDATE / DELETE on the append-only tables revoked at the schema level.

Migrations are **forward-only**. downgrade() raises NotImplementedError per
the workflow rule.

Revision ID: 0001
Revises:
Create Date: 2026-05-13 00:00:00.000000

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# --- Alembic identifiers --------------------------------------------------
revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


# --- Defaults for the dev app role.
# Production deployments pre-provision a role with rotated credentials before
# running `alembic upgrade head` and skip the CREATE ROLE step below by
# setting `streetsense.skip_role_bootstrap = 'on'` in the session.
APP_ROLE_NAME = "streetsense_app"
APP_ROLE_PASSWORD_DEV_DEFAULT = "streetsense_app"


def upgrade() -> None:
    # ----- Extensions ----------------------------------------------------
    # The postgis/postgis image already creates postgis; pgcrypto is required
    # for gen_random_uuid(). docker-entrypoint-initdb.d/01-extensions.sql
    # bootstraps both, but we issue CREATE EXTENSION IF NOT EXISTS here so
    # `alembic upgrade head` is idempotent against any reasonable Postgres.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

    # ----- road_segments --------------------------------------------------
    op.execute(
        """
        CREATE TABLE road_segments (
            id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            osm_way_id   bigint,
            geometry     geometry(LineString, 4326) NOT NULL,
            attrs        jsonb NOT NULL DEFAULT '{}'::jsonb,
            created_at   timestamptz NOT NULL DEFAULT now()
        );
        """
    )
    op.execute("CREATE INDEX road_segments_geometry_gist ON road_segments USING GIST (geometry);")
    op.execute("CREATE INDEX road_segments_osm_way_id_idx ON road_segments (osm_way_id);")

    # ----- scoring_runs ---------------------------------------------------
    # `scoring_run_timestamp` is named explicitly (rather than just `timestamp`)
    # to match the reproducibility-field naming carried into segment_scores.
    op.execute(
        """
        CREATE TABLE scoring_runs (
            id                            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            scoring_run_timestamp         timestamptz NOT NULL,
            perception_model_version      text NOT NULL,
            osm_snapshot_date             date NOT NULL,
            imagery_capture_window        daterange NOT NULL,
            propagation_algorithm_version text NOT NULL,
            notes                         text
        );
        """
    )
    op.execute(
        "CREATE INDEX scoring_runs_timestamp_btree "
        "ON scoring_runs USING BTREE (scoring_run_timestamp);"
    )

    # ----- segment_scores -------------------------------------------------
    # The six reproducibility columns are NOT NULL — refuse to record a score
    # whose provenance is unknown.
    op.execute(
        """
        CREATE TABLE segment_scores (
            id                            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            segment_id                    uuid NOT NULL REFERENCES road_segments(id),

            -- Composite + sub-scores. Sub-scores are first-class data — never
            -- collapse them in storage even if the API only ships the composite.
            composite_risk                double precision NOT NULL,
            sub_score_lane_marking        double precision,
            sub_score_glare               double precision,
            sub_score_junction_complexity double precision,
            sub_score_historical          double precision,
            confidence                    double precision,

            -- The six reproducibility fields: every score row knows where it
            -- came from. NOT NULL is the law of the land.
            scoring_run_id                uuid NOT NULL REFERENCES scoring_runs(id),
            scoring_run_timestamp         timestamptz NOT NULL,
            perception_model_version      text NOT NULL,
            osm_snapshot_date             date NOT NULL,
            imagery_capture_window        daterange NOT NULL,
            propagation_algorithm_version text NOT NULL,

            inserted_at                   timestamptz NOT NULL DEFAULT now()
        );
        """
    )
    op.execute("CREATE INDEX segment_scores_run_id_idx ON segment_scores (scoring_run_id);")
    op.execute("CREATE INDEX segment_scores_segment_id_idx ON segment_scores (segment_id);")
    op.execute(
        "CREATE INDEX segment_scores_timestamp_btree "
        "ON segment_scores USING BTREE (scoring_run_timestamp);"
    )

    # ----- Application role -----------------------------------------------
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE_NAME}') THEN
                EXECUTE format(
                    'CREATE ROLE %I LOGIN PASSWORD %L',
                    '{APP_ROLE_NAME}',
                    '{APP_ROLE_PASSWORD_DEV_DEFAULT}'
                );
            END IF;
        END
        $$;
        """
    )

    # Least-privilege grants. The app role:
    #  - reads from road_segments / scoring_runs / segment_scores
    #  - inserts into scoring_runs and segment_scores (and road_segments —
    #    ingestion writes there)
    #  - cannot UPDATE or DELETE from scoring_runs or segment_scores
    op.execute(f"GRANT USAGE ON SCHEMA public TO {APP_ROLE_NAME};")
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON road_segments TO {APP_ROLE_NAME};")
    op.execute(f"GRANT SELECT, INSERT ON scoring_runs TO {APP_ROLE_NAME};")
    op.execute(f"GRANT SELECT, INSERT ON segment_scores TO {APP_ROLE_NAME};")

    # Belt-and-braces: even if a future migration accidentally re-grants the
    # privileges, append-only is enforced by an explicit REVOKE.
    op.execute(f"REVOKE UPDATE, DELETE ON scoring_runs FROM {APP_ROLE_NAME};")
    op.execute(f"REVOKE UPDATE, DELETE ON segment_scores FROM {APP_ROLE_NAME};")


def downgrade() -> None:
    # workflow.md: migrations are forward-only.
    raise NotImplementedError("Migrations are forward-only — write a new revision.")
